### ISSUE TITLE
Website hacked?

### ISSUE THREAD

**Issue by deviant** [awestruct/awestruct.github.io#74]
https://www.awestruct.org/ has a bunch of strange advertising on it which is definitely not in this repository. Are you aware of this? Your web host might be vulnerable; perhaps switching to GitHub pages or Netlify might be a good idea?

**Comment by zbynek** [comment]
@LightGuard any ideas?

**Comment by LightGuard** [comment]
I haven't touched the website for years :) Not even sure where it's hosted or if I still have creds :)

**Comment by ramalho** [comment]
Hello, @LightGuard. Thanks for making awestruct. If you don't own the awestruct.org domain, then you should do everything in your power to prevent people from finding that hacked site which reflects very poorly on the project and may in the future present a grave security risk. The people controlling that domain may link to a different repo with a clone of your main awestruct repo infected with malicious code.

Start by renaming this repo, and removing the link to awestruct.org in the initial page of this repo. You should also consider registering a new domain a setting up a site there. Right now, anyone looking for awestruct finds a hacked site as the top result. I am sorry but ignoring the problem is not acceptable, because it may have grave consequences to potential users of your project.

**Comment by LightGuard** [comment]
I've gotten into contact with the person I think owns the domain. We'll see how quickly we can get this resolved.

**Comment by zbynek** [comment]
https://awestruct.github.io is the new website, the old hacked one should not be referenced from anywhere (awestruct gem will be updated shortly)
